### ISSUE TITLE
Do not publish to NuGet.org from feature branch

### ISSUE THREAD

**Issue by asizikov** [asizikov/github-create-repository#16]
Only `develop` and `master` branches should be published.

``` yaml
# configuration for "master" branch
# build in Release mode and deploy to Azure
-
  branches:
    only:
      - master

  configuration: Release
  deploy:
    provider: AzureCS
    ...

# configuration for all branches starting from "dev-"
# build in Debug mode and deploy locally for testing
-
  branches:
    only:
      - /dev-.*/

  configuration: Debug
  deploy:
    provider: Local
    ...

# "fall back" configuration for all other branches
# no "branches" section defined
# do not deploy at all
-
  configuration: Debug
```

http://www.appveyor.com/docs/branches
